server:
  port: 7002

spring:
  application.name: cloud-eureka-server7002

eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: false
    fetch-registry: false
    # value type is map, do not change key name, such as 'defaultZone'
    service-url:
      # single: url->self cluster: urls->others
      default-zone: http://${eureka.instance.hostname}:${server.port}/eureka/