image:
  file: .gitpod.Dockerfile

tasks:
  - before: nohup /opt/consul/consul agent -dev &> /opt/consul/nohup.out& /opt/zookeeper/start.sh
    init: cd cloud-project && mvn install
    command: ''
  - openMode: split-top
    command: echo ---top--- && git log --graph --oneline --all -n1 && echo ---cur--- && git log --graph --oneline HEAD -n1
    name: Git Panel