server:
  port: 6001

spring:
  application.name: cloud-order-service

eureka:
  client:
    register-with-eureka: true
    # watch registried client count
    fetch-registry: true
    # value type is map, do not change key name, such as 'defaultZone'
    service-url:
      defaultZone: http://localhost:7001/eureka/

CLOUD-PAYMENT-SERVICE:
  ribbon:
    connectTimeout: 2000
    readTimeout: 5000
    # retry enable
    # OkToRetryOnAllOperations: true
    # each node retry count
    # MaxAutoRetries: 0
    # retry node count
    # MaxAutoRetriesNextServer: 1
