server:
  port: 6001

spring:
  application.name: cloud-order-service

eureka:
  client:
    register-with-eureka: true
    # watch registried client count
    fetch-registry: true
    # value type is map, do not change key name, such as 'defaultZone'
    service-url:
      defaultZone: http://localhost:7001/eureka/

CLOUD-PAYMENT-SERVICE:
  ribbon:
    connectTimeout: 2000
    readTimeout: 5000
    # retry enable
    # OkToRetryOnAllOperations: true
    # each node retry count
    # MaxAutoRetries: 0
    # retry node count
    # MaxAutoRetriesNextServer: 1

feign:
  hystrix:
    enabled: true
  client:
    config:
      # provider-service-name, default means global; or use feignName: 'provider-service-name' instead
      CLOUD-PAYMENT-SERVICE:
        connectTimeout: 5000
        readTimeout: 5000
        # none(default), basic, headers, full
        loggerLevel: full

hystrix:
  command:
    # (Open)feign will generate 'className#methodName(param1Type,param2Type,...)' for each api by default, see https://github.com/OpenFeign/feign/blob/master/hystrix/README.md
    # commandKey, default means global
    'OrderServiceFeignImpl#slowGetPaymentById(Long)':
      execution.isolation.thread.timeoutInMilliseconds: 5000