server:
  port: 6006

spring:
  application.name: cloud-order-service
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        service-name: ${spring.application.name}
        prefer-ip-address: true
        # active keep-alive by self
        # heartbeat.enabled: true
        # passive keep-alive by server
        register-health-check: true
        health-check-interval: 10s
        health-check-path: /actuator/health